---

- name: install php5-fpm
  sudo: yes
  apt: pkg=php5-fpm state=installed

- name: php exact filename matching
  sudo: yes
  lineinfile: dest=/etc/php5/fpm/php.ini regexp=";cgi.fix_pathinfo" line="cgi.fix_pathinfo=1" state=present

- name: php listen on socket not port
  sudo: yes
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp="listen = 127.0.0.1:9000" line="listen = /var/run/php5-fpm.sock" state=present

- name: Restart php5-fpm
  sudo: yes
  service: name=php5-fpm state=restarted