---
- hosts: all
  user: deploy
  sudo: no
  vars_prompt:
    - name: "s3cmd_accessKey"
      prompt: "Please enter your s3 access key"
      private: no
    - name: "s3cmd_secretKey"
      prompt: "Please enter your s3 secret key"
      private: no
  pre_tasks:
    - name: establish more facts
      action: server_facts
  roles:
    - s3cmd
    - nginx
    - node
    - mongo
    - scala
  tasks:
    - name: create site folder
      file: path=${web_dir}/${app_name}/ state=directory owner=deploy

    - name: create log folder
      file: path=${web_dir}/${app_name}/log/ state=directory owner=deploy

    - name: create src folder
      file: path=${web_dir}/${app_name}/src/ state=directory owner=deploy

    - name: create ssl folder
      file: path=${web_dir}/${app_name}/ssl/ state=directory owner=deploy