--- 

- name: create site folder
  file: path={{web_dir}}/{{app_name}}/ state=directory owner=deploy

- name: create log folder
  file: path={{web_dir}}/{{app_name}}/log/ state=directory owner=deploy

- name: create src folder
  file: path={{web_dir}}/{{app_name}}/src/ state=directory owner=deploy

- name: create ssl folder
  file: path={{web_dir}}/{{app_name}}/ssl/ state=directory owner=deploy