- name: Copy production SSL certificate chain
  copy: src={{server_address}}.pem dest={{web_dir}}/{{app_name}}/ssl/{{server_address}}.pem

- name: Copy production SSL key
  copy: src={{server_address}}.key dest={{web_dir}}/{{app_name}}/ssl/{{server_address}}.key
