---

- name: install common packages needed for node development
  sudo: yes
  apt: pkg=$item state=installed
  when_string: $installed_node_version != $node_version
  with_items:
    - g++
    - curl
    - libssl-dev
    - apache2-utils
    - git-core
    - make

- name: fetch node source code
  command: wget http://nodejs.org/dist/${node_version}/node-${node_version}.tar.gz
  when: installed_node_version != node_version

- name: expand node source code
  command: tar xzf node-${node_version}.tar.gz
  when: installed_node_version != node_version

- name: configure node
  command: chdir=/home/deploy/node-${node_version} ./configure
  when: installed_node_version != node_version

- name: make node
  command: chdir=/home/deploy/node-${node_version} make -j 3
  when: installed_node_version != node_version

- name: install node
  command: chdir=/home/deploy/node-${node_version} make install
  when: installed_node_version != node_version

- name: clean node build directory
  file: path=node-${node_version} state=absent
  when: installed_node_version != node_version

- name: clean node source file
  file: path=node-${node_version}.tar.gz state=absent
  when: installed_node_version != node_version
  
- name: install forever (takes forever ... ;-) )
  npm:  name=forever global=yes

- name: install bower
  npm:  name=bower global=yes