---
- hosts: dev-stocksystem
  user: vagrant
  sudo: yes
  vars_prompt:
    - name: "s3cmd_accessKey"
      prompt: "Please enter your s3 access key"
      private: no
    - name: "s3cmd_secretKey"
      prompt: "Please enter your s3 secret key"
      private: no
    - name: "logwatch_email"
      prompt: "Please enter the email you want logwatch to send daily updates"
      private: no
  roles:
    - common